import Vue from 'vue'
import '../assets/styles/element-variables.scss'
import { Button, Alert, DatePicker, Option, OptionGroup, Timeline, Tabs, TabPane, Tag, Pagination, Carousel, CarouselItem, Divider, Link, Select, Dialog, Switch, Dropdown, DropdownItem, DropdownMenu, MessageBox, Upload, Form, FormItem, Input, Container, Header, Main, Submenu, MenuItem, Menu, MenuItemGroup, Aside, Breadcrumb, BreadcrumbItem, Card, Row, Col, Table, TableColumn, Message, TimelineItem, Popover, Progress } from 'element-ui'

Vue.use(Button)
Vue.use(Tabs)
Vue.use(Option)
Vue.use(OptionGroup)
Vue.use(DatePicker)
Vue.use(TabPane)
Vue.use(Tag)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Main)
Vue.use(Aside)
Vue.use(Submenu)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Pagination)
Vue.use(Upload)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Switch)
Vue.use(Dialog)
Vue.use(Select)
Vue.use(Link)
Vue.use(Divider)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Alert)
Vue.use(Timeline)
Vue.use(TimelineItem)
Vue.use(Popover)
Vue.use(Progress)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
Vue.prototype.$prompt = MessageBox.prompt
